name: condosocio
description: A new Flutter project.
publish_to: "none"
version: 7.0.1+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  edge_alert: ^0.0.1
  email_validator: ^2.0.1
  flutter_html: ^3.0.0-alpha.2
  flutter_icons: ^1.1.0
  flutter_svg: ^1.0.3
  get: null
  get_storage: null
  google_fonts: ^2.0.0
  http: ^0.13.0
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+11
  local_auth: ^2.1.2
  mask_text_input_formatter: ^2.1.0
  permission_handler: ^9.2.0
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.2
  shared_preferences: ^2.0.3
  url_launcher: ^6.1.6
  flutter_speed_dial: ^5.0.0+1
  onesignal_flutter: ^3.4.1
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  table_calendar: ^3.0.0
  in_app_review: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
