name: condosocio
description: A new Flutter project.
publish_to: "none"
version: 7.0.1+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter_html: ^3.0.0-alpha.2
  flutter_svg: ^1.0.3
  get: null
  get_storage: null
  google_fonts: ^4.0.4
  http: ^0.13.0
  image_cropper: ^1.5.0
  image_picker: ^0.8.6
  local_auth: ^2.1.2
  mask_text_input_formatter: ^2.1.0
  permission_handler: ^9.2.0
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.6
  shared_preferences: ^2.0.3
  url_launcher: ^6.1.6
  flutter_speed_dial: ^5.0.0+1
  onesignal_flutter: ^3.5.1
  qr_flutter: ^4.1.0
  intl: ^0.18.0
  table_calendar: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_animated_dialog: ^2.0.1
  lottie: ^2.3.2
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
