name: condosocio
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  contacts_service: ^0.4.6
  cupertino_icons: ^1.0.2
  edge_alert: ^0.0.1
  email_validator: ^1.0.6
  flutter_html: ^1.3.0
  flutter_icons: ^1.1.0
  flutter_open_whatsapp: ^0.1.2
  flutter_svg: ^0.20.0-nullsafety.3
  get: null
  get_storage: null
  google_fonts: ^2.0.0
  http: ^0.13.0
  image_cropper: ^1.4.0
  image_picker: ^0.7.2
  local_auth: ^1.1.0
  mask_text_input_formatter: ^1.2.1
  permission_handler: ^6.1.1
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.2
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.2
  flutter_speed_dial: ^3.0.5
  onesignal_flutter: ^2.6.3
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  table_calendar: ^3.0.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
 
