allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def newBuildDir = rootProject.layout.buildDirectory.dir("../../build").get()
rootProject.layout.buildDirectory.set(newBuildDir)

subprojects {
    layout.buildDirectory.set(newBuildDir.dir(name))
    project.evaluationDependsOn(":app")
}

gradle.afterProject { proj ->
    if (proj.plugins.hasPlugin('com.android.library')) {
        proj.android {
            compileSdkVersion 36
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
